// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using chat.Models;

#nullable disable

namespace chat.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    [Migration("20230616082337_ModifiedUser2")]
    partial class ModifiedUser2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("chat.Models.Dialog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstUserTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SecondUserTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FirstUserTag");

                    b.HasIndex("SecondUserTag");

                    b.ToTable("StartedDialogs");
                });

            modelBuilder.Entity("chat.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SendTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SenderTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverTag");

                    b.HasIndex("SenderTag");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("chat.Models.TestTable", b =>
                {
                    b.Property<int>("F1")
                        .HasColumnType("int")
                        .HasColumnName("f1");

                    b.Property<string>("F2")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("f2");

                    b.Property<bool?>("F3")
                        .HasColumnType("bit");

                    b.HasKey("F1")
                        .HasName("PK__testTabl__32139E58AAB0015F");

                    b.ToTable("testTable", (string)null);
                });

            modelBuilder.Entity("chat.Models.User", b =>
                {
                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Tag");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("chat.Models.Dialog", b =>
                {
                    b.HasOne("chat.Models.User", "FirstUser")
                        .WithMany()
                        .HasForeignKey("FirstUserTag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("chat.Models.User", "SecondUser")
                        .WithMany()
                        .HasForeignKey("SecondUserTag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FirstUser");

                    b.Navigation("SecondUser");
                });

            modelBuilder.Entity("chat.Models.Message", b =>
                {
                    b.HasOne("chat.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverTag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("chat.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderTag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });
#pragma warning restore 612, 618
        }
    }
}
